# Generated by Django 4.2.4 on 2023-09-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='fechaCreacion',
        ),
        migrations.AddField(
            model_name='categorias',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
